"""create synthetic banking schema

Revision ID: d03942078cd2
Revises: 
Create Date: 2026-09-23 01:36:48.986063

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd03942078cd2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('authentication_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'LOCKED', 'CLOSED')", name='ck_customers_status'),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('masked_account_number', sa.String(length=32), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('checking', 'savings')", name='ck_accounts_account_type'),
    sa.CheckConstraint("status IN ('ACTIVE', 'FROZEN', 'CLOSED')", name='ck_accounts_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('masked_account_number')
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_table('support_cases',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('handoff_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')", name='ck_support_cases_priority'),
    sa.CheckConstraint("status IN ('OPEN', 'ESCALATED', 'RESOLVED', 'CLOSED')", name='ck_support_cases_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_support_cases_customer_id'), 'support_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_support_cases_session_id'), 'support_cases', ['session_id'], unique=False)
    op.create_table('cards',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('masked_card_number', sa.String(length=32), nullable=False),
    sa.Column('card_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expiration_month', sa.Integer(), nullable=False),
    sa.Column('expiration_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'FROZEN', 'LOST', 'STOLEN', 'CLOSED')", name='ck_cards_status'),
    sa.CheckConstraint('expiration_month BETWEEN 1 AND 12', name='ck_cards_expiration_month'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('masked_card_number')
    )
    op.create_index(op.f('ix_cards_account_id'), 'cards', ['account_id'], unique=False)
    op.create_index(op.f('ix_cards_customer_id'), 'cards', ['customer_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=False),
    sa.Column('merchant_category', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('transaction_type', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'POSTED', 'REVERSED', 'DECLINED')", name='ck_transactions_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_card_id'), 'transactions', ['card_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_timestamp'), 'transactions', ['transaction_timestamp'], unique=False)
    op.create_table('disputes',
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', 'CANCELLED')", name='ck_disputes_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('dispute_id')
    )
    op.create_index(op.f('ix_disputes_customer_id'), 'disputes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_disputes_transaction_id'), 'disputes', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disputes_transaction_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_customer_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_transactions_transaction_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_card_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_cards_customer_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_account_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_support_cases_session_id'), table_name='support_cases')
    op.drop_index(op.f('ix_support_cases_customer_id'), table_name='support_cases')
    op.drop_table('support_cases')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
