"""allow unauthenticated support escalation

Revision ID: d2a42313c6f8
Revises: d03942078cd2
Create Date: 2026-09-23 02:59:08.902112

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd2a42313c6f8'
down_revision: str | Sequence[str] | None = 'd03942078cd2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_cases', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_cases', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
